title: "ꜱᴇᴛᴛɪɴɢꜱ"
rows: 3

items:
  status_on:
    name: "&aᴏɴ"
  status_off:
    name: "&cᴏꜰꜰ"

  enabled:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
  disabled:
    sound: BLOCK_LEVER_CLICK

  tpa_confirm_menu:
    material: FEATHER
    name: "&f"
    lore:
      - "&r  <b><gradient:#5b29ff:#8f00fc>ᴛᴘᴀ ᴄᴏɴꜰɪʀᴍ ᴍᴇɴᴜ</gradient></b>&r"
      - "&r        &8&m               &r"
      - ""
      - "&r &8• &fꜱᴛᴀᴛᴜꜱ: %status% &8•&r"
      - ""
      - "&r &8• &#8f00fcᴄʟɪᴄᴋ &fᴛᴏ ᴛᴏɢɢʟᴇ &8•&r"
      - ""
    slot: 10
  tpa_requests:
    material: ENDER_PEARL
    name: "&f"
    lore:
      - "&r  <b><gradient:#5b29ff:#8f00fc>ᴛᴘᴀ ʀᴇQᴜᴇꜱᴛꜱ</gradient></b>&r"
      - "&r     &8&m               &r"
      - ""
      - "&r &8• &fꜱᴛᴀᴛᴜꜱ: %status% &8•&r"
      - ""
      - "&r &8• &#8f00fcᴄʟɪᴄᴋ &fᴛᴏ ᴛᴏɢɢʟᴇ &8•&r"
      - ""
    slot: 11
  tpa_here_requests:
    material: ENDER_EYE
    name: "&f"
    lore:
      - "&r  <b><gradient:#5b29ff:#8f00fc>ᴛᴘᴀ ʜᴇʀᴇ ʀᴇQᴜᴇꜱᴛꜱ</gradient></b>&r"
      - "&r         &8&m               &r"
      - ""
      - "&r &8• &fꜱᴛᴀᴛᴜꜱ: %status% &8•&r"
      - ""
      - "&r &8• &#8f00fcᴄʟɪᴄᴋ &fᴛᴏ ᴛᴏɢɢʟᴇ &8•&r"
      - ""
    slot: 12
  tp_auto:
    material: GOAT_HORN
    name: "&f"
    lore:
      - "&r     <b><gradient:#5b29ff:#8f00fc>ᴛᴘ ᴀᴜᴛᴏ</gradient></b>&r"
      - "&r       &8&m        &r"
      - ""
      - "&r &8• &fꜱᴛᴀᴛᴜꜱ: %status% &8•&r"
      - ""
      - "&r &8• &#8f00fcᴄʟɪᴄᴋ &fᴛᴏ ᴛᴏɢɢʟᴇ &8•&r"
      - ""
    slot: 14
  tpa_accept:
    material: GOLD_NUGGET
    name: "&f"
    lore:
      - "&r  <b><gradient:#5b29ff:#8f00fc>ᴛᴘᴀ ᴀᴄᴄᴇᴘᴛ ᴍᴇɴᴜ</gradient></b>&r"
      - "&r       &8&m               &r"
      - ""
      - "&r &8• &fꜱᴛᴀᴛᴜꜱ: %status% &8•&r"
      - ""
      - "&r &8• &#8f00fcᴄʟɪᴄᴋ &fᴛᴏ ᴛᴏɢɢʟᴇ &8•&r"
      - ""
    slot: 15
  back_confirm:
    material: COMPASS
    name: "&f"
    lore:
      - "&r  <b><gradient:#5b29ff:#8f00fc>ʙᴀᴄᴋ ᴄᴏɴꜰɪʀᴍ ᴍᴇɴᴜ</gradient></b>&r"
      - "&r       &8&m               &r"
      - ""
      - "&r &8• &fꜱᴛᴀᴛᴜꜱ: %status% &8•&r"
      - ""
      - "&r &8• &#8f00fcᴄʟɪᴄᴋ &fᴛᴏ ᴛᴏɢɢʟᴇ &8•&r"
      - ""
    slot: 16